// Bilingual copy + listing data. All content placeholder-realistic; swap for real listings.
const T={
he:{nav:{found:'יסודות',land:'דף הבית',list:'נכסים',phone:'מובייל'},brand:'נדל״ן זה בית',sub:'HOME REAL ESTATE',
contact:'צרו קשר',call:'התקשרו',wa:'וואטסאפ',save:'שמירה',all:'כל הפרטים',less:'פחות פרטים',
heroKick:'מוכרים דירה בתל אביב',heroH:['אנחנו לא מוכרים נכסים.','אנחנו מוכרים בתים.'],
heroP:'הערכת שווי אמיתית, שיווק שמראה את הדירה כמו שהיא באמת, וניהול משא ומתן עד החתימה. 12 שנה באותן שכונות.',
cta1:'להערכת שווי חינם',cta2:'לצפייה בנכסים',
stats:[['12','שנים בשוק התל אביבי'],['400+','דירות שנמכרו'],['28','ימים בממוצע למכירה'],['98%','מהמחיר המבוקש']],
stepsKick:'איך מוכרים איתנו',stepsH:'שלושה שלבים, בלי הפתעות',
steps:[['01','הערכת שווי','פגישה בנכס, השוואת עסקאות שנסגרו באותו רחוב ובאותה קומה, וטווח מחיר שאנחנו מוכנים לעמוד מאחוריו.'],['02','שיווק וצילום','צילום מקצועי באור יום, תיאור מדויק, ופרסום בכל הפלטפורמות. סינון פניות לפני שאתם פוגשים מישהו.'],['03','משא ומתן וסגירה','מנהלים את המשא ומתן מולכם בשקיפות מלאה, מלווים את הבדיקות המשפטיות ועד למסירת המפתח.']],
featKick:'נכסים נבחרים',featH:'מה שיש עכשיו בשכונות שלנו',featAll:'לכל הנכסים',
qKick:'לקוחות',qH:'מה אומרים אחרי החתימה',
quotes:[['מכרנו את הדירה בפלורנטין בתוך שלושה שבועות, במחיר שלא האמנו שנקבל. אריק לא הבטיח מה שלא יכול לעשות.','ד״ר, מוכרת, פלורנטין'],['קנינו דירה ראשונה והרגשנו שמישהו שומר עלינו בכל שלב, כולל מול עורך הדין של המוכר.','י׳ ונ׳, קונים, לב העיר'],['השוויתי שלוש סוכנויות. רק כאן קיבלתי הסבר מסודר איך נקבע המחיר, עם עסקאות אמיתיות מול העיניים.','א׳, מוכר, הצפון הישן']],
aboutKick:'המשרד',aboutH:'מרכז בעלי מלאכה 5, תל אביב',
aboutP:['המשרד פתוח לפגישות בתיאום מראש. יושבים, מסתכלים על מספרים אמיתיים, ומחליטים אם יש כאן עסקה.','אריק נעים מלווה מוכרים וקונים בתל אביב מ־2014. אותו איש קשר מהפגישה הראשונה ועד המסירה.'],
slot:'תמונת המשרד — גרור תמונה לכאן',
formKick:'הערכת שווי',formH:'נשמח לחזור אליכם היום',
f:{name:'שם מלא',phone:'טלפון',addr:'כתובת הנכס',type:'סוג הנכס',msg:'משהו שכדאי שנדע',send:'שלחו בקשה',
eName:'נא למלא שם',ePhone:'מספר טלפון לא תקין',eAddr:'נא למלא כתובת',sent:'הבקשה נשלחה. נחזור אליכם היום, בין 09:00 ל־20:00.'},
filters:{hood:'שכונה',price:'טווח מחיר',type:'סוג נכס',any:'הכל',results:n=>`${n} נכסים`,none:'אין נכסים שמתאימים לסינון'},
fields:{type:'סוג',city:'עיר',hood:'שכונה',street:'רחוב',price:'מחיר',rooms:'חדרים',size:'שטח',balcony:'מרפסת',floor:'קומה',floors:'קומות בבניין',exposure:'כיווני אוויר',parking:'חניה',storage:'מחסן',basement:'מרתף',shabbat:'מעלית שבת',access:'נגישות',year:'שנת בנייה',cond:'מצב',chars:'מאפיינים',poi:'בסביבה',desc:'תיאור',yes:'יש',no:'אין'},
rooms:'חדרים',sqm:'מ״ר',floorOf:(a,b)=>`קומה ${a} מתוך ${b}`,expo:n=>`${n} כיווני אוויר`,
waMsg:a=>`שלום, מתעניין בנכס ב${a} שראיתי באתר.`,
foundKick:'יסודות המערכת',foundH:'צבע, טיפוגרפיה ורכיבים',
fColor:'צבע',fType:'טיפוגרפיה',fBtn:'כפתורים ותגיות',fCard:'כרטיס נכס',fNav:'ניווט',
colorNote:'אין שחור ואין לבן טהור בטקסט. הכהה הוא ירוק כהה #1C3F17, הקרקע לבן #FFFFFF, והניאון #5CFF7A הוא קו, מסגרת והילה — לא שטח.',
typeNote:'Heebo לעברית · Archivo ללטינית. משקלים תואמים 300/400/500. כותרות לא עוברות משקל 500 — ההיררכיה היא גודל ורווח.',
phoneKick:'מובייל',phoneH:'כרטיס נכס בטלפון'},
en:{nav:{found:'Foundation',land:'Home',list:'Properties',phone:'Mobile'},brand:'Home Real Estate',sub:'נדל״ן זה בית',
contact:'Contact',call:'Call',wa:'WhatsApp',save:'Save',all:'All details',less:'Fewer details',
heroKick:'Selling an apartment in Tel Aviv',heroH:['We don\u2019t sell properties.','We sell homes.'],
heroP:'A real valuation, marketing that shows the apartment as it actually is, and negotiation handled through to signature. Twelve years in the same neighborhoods.',
cta1:'Free valuation',cta2:'Browse properties',
stats:[['12','Years in the Tel Aviv market'],['400+','Apartments sold'],['28','Average days to sale'],['98%','Of asking price']],
stepsKick:'Selling with us',stepsH:'Three steps, no surprises',
steps:[['01','Valuation','A meeting at the property, comparable closed deals on the same street and floor, and a price range we stand behind.'],['02','Marketing & photography','Professional daylight photography, an accurate description, listings on every platform, and enquiries screened before you meet anyone.'],['03','Negotiation & closing','We run the negotiation with full transparency, support the legal checks, and stay through to handover.']],
featKick:'Selected properties',featH:'What\u2019s available in our neighborhoods',featAll:'All properties',
qKick:'Clients',qH:'What people say after signing',
quotes:[['We sold our Florentin apartment in three weeks, at a price we didn\u2019t believe we\u2019d get. Arik never promised what he couldn\u2019t deliver.','Seller, Florentin'],['We bought our first apartment and felt looked after at every stage, including with the seller\u2019s lawyer.','Buyers, City Center'],['I compared three agencies. Only here did I get a proper explanation of how the price was set, with real deals in front of me.','Seller, Old North']],
aboutKick:'The office',aboutH:'Merkaz Baalei Melacha 5, Tel Aviv',
aboutP:['Open for meetings by appointment. We sit down, look at real numbers, and decide whether there\u2019s a deal here.','Arik Naim has worked with sellers and buyers in Tel Aviv since 2014. The same point of contact from first meeting to handover.'],
slot:'Office photograph — drop an image here',
formKick:'Valuation',formH:'We\u2019ll get back to you today',
f:{name:'Full name',phone:'Phone',addr:'Property address',type:'Property type',msg:'Anything we should know',send:'Send request',
eName:'Please enter a name',ePhone:'Invalid phone number',eAddr:'Please enter an address',sent:'Request sent. We\u2019ll get back to you today, between 09:00 and 20:00.'},
filters:{hood:'Neighborhood',price:'Price range',type:'Property type',any:'All',results:n=>`${n} properties`,none:'No properties match these filters'},
fields:{type:'Type',city:'City',hood:'Neighborhood',street:'Street',price:'Price',rooms:'Rooms',size:'Size',balcony:'Balcony',floor:'Floor',floors:'Floors in building',exposure:'Exposure',parking:'Parking',storage:'Storage',basement:'Basement',shabbat:'Shabbat elevator',access:'Accessible',year:'Year built',cond:'Condition',chars:'Characteristics',poi:'Nearby',desc:'Description',yes:'Yes',no:'No'},
rooms:'rooms',sqm:'m²',floorOf:(a,b)=>`Floor ${a} of ${b}`,expo:n=>`${n} exposures`,
waMsg:a=>`Hello, I\u2019m interested in the property at ${a} I saw on your site.`,
foundKick:'System foundation',foundH:'Color, type and components',
fColor:'Color',fType:'Typography',fBtn:'Buttons & tags',fCard:'Property card',fNav:'Navigation',
colorNote:'No black and no pure white in text. The dark is deep green #1C3F17, the ground is white #FFFFFF, and the neon #5CFF7A is a line, an outline and a glow — never a field.',
typeNote:'Heebo for Hebrew · Archivo for Latin. Matched weights 300/400/500. Headings never go past 500 — hierarchy is size and space.',
phoneKick:'Mobile',phoneH:'Property card on a phone'}};

const CH={renov:['משופצת','Renovated'],mamad:['ממ״ד','Safe room'],balc:['מרפסת שמש','Sun balcony'],ac:['מיזוג','Air conditioning'],quiet:['רחוב שקט','Quiet street'],tama:['תמ״א 38','Tama 38'],bright:['מוארת','Bright'],high:['תקרות גבוהות','High ceilings'],entr:['כניסה פרטית','Private entrance'],sea:['נוף לים','Sea view'],now:['כניסה מיידית','Immediate entry'],shabbat:['מעלית שבת','Shabbat elevator']};
const POI={school:['בתי ספר','Schools'],kinder:['גנים','Kindergartens'],park:['פארק','Park'],beach:['הים','Beach'],rail:['הרכבת הקלה','Light rail'],bus:['קווי אוטובוס','Bus lines'],super:['סופרמרקט','Supermarket'],cafe:['בתי קפה','Cafés'],syn:['בית כנסת','Synagogue']};
const COND={new:['חדשה מקבלן','New from contractor'],likenew:['כמו חדשה','Like new'],renov:['משופצת','Renovated'],kept:['שמורה','Well maintained'],good:['במצב טוב','Good condition'],needs:['דורשת שיפוץ','Needs renovation'],demo:['להריסה ובנייה','For demolition']};
const TYPES={apt:['דירה','Apartment'],garden:['דירת גן','Garden apartment'],pent:['פנטהאוז','Penthouse'],duplex:['דופלקס','Duplex'],villa:['בית פרטי','Private house'],cottage:['קוטג׳','Cottage'],studio:['סטודיו','Studio'],roof:['דירת גג','Roof apartment']};
const HOODS={center:['לב העיר','City Center'],florentin:['פלורנטין','Florentin'],nevetzedek:['נווה צדק','Neve Tzedek'],oldnorth:['הצפון הישן','Old North'],ramataviv:['רמת אביב','Ramat Aviv'],kerem:['כרם התימנים','Kerem HaTeimanim']};

const LISTINGS=[
{id:'l1',type:'garden',hood:'center',street:['רוטשילד 42','Rothschild 42'],price:4250000,rooms:4,size:112,balcony:14,floor:2,floors:5,expN:3,expD:['מזרח · דרום · מערב','E · S · W'],parking:1,storage:1,basement:0,shabbat:1,access:1,year:1998,cond:'renov',status:['חדש','New'],
chars:['renov','mamad','balc','quiet','tama'],poi:['school','park','rail','cafe'],
teaser:['משופצת מהיסוד, מרפסת שמש 14 מ״ר לדרום, ממ״ד וחניה בטאבו.','Fully renovated, a 14 m² south-facing sun balcony, safe room and deeded parking.'],
desc:['דירת גן בבניין קטן ומטופח על רוטשילד, אחרי שיפוץ יסודי שכלל אינסטלציה וחשמל. שלושה כיווני אוויר, ממ״ד, מרפסת שמש פונה לדרום ומחסן בקומת הקרקע. הבניין עבר תמ״א 38 ויש מעלית שבת. הכניסה מיידית.','A garden apartment in a small, well-kept building on Rothschild, after a full renovation including plumbing and electrics. Three exposures, a safe room, a south-facing sun balcony and ground-floor storage. The building completed Tama 38 and has a Shabbat elevator. Immediate entry.']},
{id:'l2',type:'apt',hood:'florentin',street:['וייטל 8','Vital 8'],price:2790000,rooms:3,size:74,balcony:6,floor:3,floors:4,expN:2,expD:['מזרח · מערב','E · W'],parking:0,storage:1,basement:0,shabbat:0,access:0,year:1952,cond:'kept',status:['',''],
chars:['bright','high','quiet','now'],poi:['cafe','bus','super','syn'],
teaser:['דירה בבניין באוהאוס שמור, תקרות 3.10 מ׳ ואור מכל צד.','A well-kept Bauhaus building, 3.10 m ceilings and light from every side.'],
desc:['שלושה חדרים בקומה שלישית בבניין באוהאוס שמור, בלי מעלית. תקרות 3.10 מ׳, חלונות מקוריים ואור לאורך כל היום. מרפסת שירות הוסבה למרפסת קטנה. מחסן בחצר. אזור בתי הקפה של פלורנטין בהליכה של דקה.','A third-floor three-room apartment in a preserved Bauhaus building, no elevator. Ceilings of 3.10 m, original windows and light throughout the day. The service balcony was converted into a small terrace. Storage in the yard. The Florentin cafés are a minute away.']},
{id:'l3',type:'pent',hood:'oldnorth',street:['אבן גבירול 121','Ibn Gabirol 121'],price:9800000,rooms:5,size:186,balcony:42,floor:9,floors:9,expN:4,expD:['ארבעה כיוונים','All four'],parking:2,storage:1,basement:0,shabbat:1,access:1,year:2016,cond:'likenew',status:['בבלעדיות','Exclusive'],
chars:['sea','balc','mamad','ac','renov'],poi:['park','beach','school','super'],
teaser:['פנטהאוז בקומה תשיעית, מרפסת 42 מ״ר ונוף פתוח לים.','A ninth-floor penthouse, a 42 m² terrace and an open sea view.'],
desc:['פנטהאוז בבניין בוטיק מ־2016, בקומה האחרונה בלבד. חמישה חדרים, ארבעה כיווני אוויר, מרפסת 42 מ״ר עם נוף לים ולפארק. שתי חניות בטאבו ומחסן. ממ״ד, מיזוג מיני מרכזי, מעלית שבת.','A penthouse in a 2016 boutique building, sole occupant of the top floor. Five rooms, four exposures, a 42 m² terrace overlooking the sea and the park. Two deeded parking spaces and storage. Safe room, central air conditioning, Shabbat elevator.']},
{id:'l4',type:'studio',hood:'kerem',street:['נחליאלי 3','Nahalieli 3'],price:1690000,rooms:1.5,size:38,balcony:0,floor:1,floors:3,expN:1,expD:['דרום','S'],parking:0,storage:0,basement:0,shabbat:0,access:0,year:1948,cond:'good',status:['',''],
chars:['bright','now','quiet'],poi:['beach','cafe','bus','super'],
teaser:['סטודיו קומפקטי בכרם, שתי דקות מהשוק ומהים.','A compact studio in the Kerem, two minutes from the market and the sea.'],
desc:['סטודיו של 38 מ״ר בקומה ראשונה בסמטה שקטה בכרם התימנים. מטבח פתוח, חדר רחצה מחודש, כיוון דרום. מתאים למשקיע או לדירת עיר. הים והשוק בהליכה קצרה.','A 38 m² first-floor studio on a quiet lane in Kerem HaTeimanim. Open kitchen, refurbished bathroom, south-facing. Suits an investor or a city pied-à-terre. The beach and the market are a short walk away.']},
{id:'l5',type:'duplex',hood:'nevetzedek',street:['שבזי 21','Shabazi 21'],price:6400000,rooms:4.5,size:141,balcony:18,floor:2,floors:3,expN:3,expD:['צפון · מזרח · מערב','N · E · W'],parking:1,storage:1,basement:1,shabbat:0,access:0,year:1930,cond:'renov',status:['חדש','New'],
chars:['renov','high','entr','balc','quiet'],poi:['cafe','school','beach','bus'],
teaser:['דופלקס בבית טמפלרי משוחזר, כניסה פרטית ומרתף.','A duplex in a restored Templar house, private entrance and basement.'],
desc:['דופלקס בבית משוחזר משנות השלושים בשבזי, עם כניסה פרטית מהחצר. שני מפלסים, ארבעה חדרים וחצי, מרפסת 18 מ״ר ומרתף בשימוש. שוחזר ב־2021 בשמירה על החלונות והרצפות המקוריות. חניה בטאבו.','A duplex in a restored 1930s house on Shabazi, with a private entrance from the courtyard. Two levels, four and a half rooms, an 18 m² terrace and a usable basement. Restored in 2021, keeping the original windows and floors. Deeded parking.']},
{id:'l6',type:'apt',hood:'ramataviv',street:['ברודצקי 34','Brodetsky 34'],price:3980000,rooms:4,size:104,balcony:11,floor:6,floors:12,expN:3,expD:['דרום · מזרח · מערב','S · E · W'],parking:1,storage:1,basement:0,shabbat:1,access:1,year:1978,cond:'needs',status:['',''],
chars:['mamad','ac','shabbat','quiet'],poi:['school','kinder','park','super','bus'],
teaser:['ארבעה חדרים מול הפארק, דורשת שיפוץ — מחיר בהתאם.','Four rooms facing the park, needs renovation — priced accordingly.'],
desc:['ארבעה חדרים בקומה שישית בבניין מטופח ברמת אביב, מול הפארק. הדירה במצב מקורי ודורשת שיפוץ, והמחיר מגלם את זה. ממ״ד, מרפסת 11 מ״ר, חניה ומחסן. מעלית שבת. בתי ספר וגנים בהליכה.','A sixth-floor four-room apartment in a well-kept Ramat Aviv building, facing the park. Original condition, needs renovation, and the price reflects it. Safe room, an 11 m² balcony, parking and storage. Shabbat elevator. Schools and kindergartens within walking distance.']}];

const PRICE_BANDS=[{k:'a',he:'עד 3 מ׳',en:'Up to ₪3M',max:3000000},{k:'b',he:'3–5 מ׳',en:'₪3–5M',min:3000000,max:5000000},{k:'c',he:'5–8 מ׳',en:'₪5–8M',min:5000000,max:8000000},{k:'d',he:'8 מ׳ ומעלה',en:'₪8M+',min:8000000}];
const CONTACT={agent:['אריק נעים','Arik Naim'],phone:'050-7464403',addr:['מרכז בעלי מלאכה 5, תל אביב','Merkaz Baalei Melacha 5, Tel Aviv'],hours:['א׳–ה׳ 09:00–20:00 · ו׳ 09:00–13:00','Sun–Thu 09:00–20:00 · Fri 09:00–13:00']};
